# Generated by Django 6.1.1 on 2026-09-28 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0003_load_classes'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subject',
            options={'ordering': ['order', 'id']},
        ),
        migrations.AlterModelOptions(
            name='teacher',
            options={'ordering': ['order', 'id']},
        ),
        migrations.AddField(
            model_name='subject',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='teacher',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
